image: docker:latest
variables:
  DOCKER_USERNAME: "registry"
  DOCKER_REGISTRY: "registry.we-program-it.com"
  DOCKER_REPOSITORY: "vpecquerie/ansible-configuration"

services:
  - docker:dind

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY

build_server:
  stage: build
  script:
    - docker build --pull -t "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:server" -f Dockerfile_server .
    - docker push "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:server"


build_desktop:
  stage: build
  script:
    - docker build --pull -t "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:desktop" -f Dockerfile_desktop .
    - docker push "$DOCKER_REGISTRY/$DOCKER_REPOSITORY:desktop"
  except:
    - master